type BaseAdData = {
  id?: string | number | null;
  slug?: string | null;
  title?: string | null;
  brand?: string | null;
  model?: string | null;
  version?: string | null;
  year?: string | number | null;
  yearLabel?: string | null;
  year_model?: string | number | null;
  city?: string | null;
  state?: string | null;
  price?: number | string | null;
  mileage?: number | string | null;
  image?: string | null;
  image_url?: string | null;
  cover_image?: string | null;
  badge?: string | null;
  below_fipe?: boolean | null;
  highlight_until?: string | null;
  catalogWeight?: 1 | 2 | 3 | 4 | null;
  plan?: string | null;
  dealership_id?: string | number | null;
  dealership_name?: string | null;
  dealer_name?: string | null;
  seller_type?: string | null;
};
